spring:
  application:
    name: queue-with-local-message

  # mysql
  datasource:
    url: jdbc:mysql://localhost/test
    username: root

  # rabbitmq
  rabbitmq:
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 4000
        auto-startup: true
        prefetch: 30 # 2个consumer的情况下，unack消息60个的时候就不再接收消息了，造成“消息阻塞”
      type: direct
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 4000
      mandatory: true
    publisher-confirm-type: correlated
    publisher-returns: true
    host: localhost
    username: guest
    password: guest
    port: 5672

